name: Delta Integration Tests - Hash partitioning
on:
  pull_request:
    paths:
      - 'delta/**'
      - 'pekko/**'
      - 'tests/**'
      - 'build.sbt'
      - 'project/**'
      - '.github/workflows/ci-integration-hash-tests.yml'
jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 40
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      PARTITION_STRATEGY: 'hash'
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: Setup JDK
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'sbt'
          check-latest: true
      - name: Setup SBT
        uses: sbt/setup-sbt@v1
      - name: Clean, build Delta image
        run: |
          sbt -Dsbt.color=always -Dsbt.supershell=false \
            clean \
            app/Docker/publishLocal
      - name: Start services
        run: docker compose -f tests/docker/delta-blazegraph-compose.yml up --wait
        timeout-minutes: 2
      - name: Test
        run: sbt -Dsbt.color=always -Dsbt.supershell=false "project tests" test
      - name: Stop & clean Docker
        if: ${{ always() }}
        run: |
          docker compose -f tests/docker/delta-blazegraph-compose.yml down --rmi "local" --volumes
          docker system prune --force --volumes