name: Website
on:
  pull_request:
    branches: [website]
  push:
    branches: [website]

jobs:
  build_publish:
    name: Generate Website
    runs-on: ubuntu-latest
    timeout-minutes: 20
    permissions:
      contents: write
    strategy:
      fail-fast: true
    steps:
      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          check-latest: true
      - name: Setup SBT
        uses: sbt/setup-sbt@v1
      - name: Checkout
        uses: actions/checkout@v5
        with:
          submodules: true
      - name: Coursier Cache
        uses: coursier/cache-action@v6
      - name: Build Website
        run: ./build.sh
      - name: Publish website
        if: github.event_name != 'pull_request'
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./target
          publish_branch: gh-pages
